# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Fallstudie I - Tabelle 
author: Jana Plomin, Juliane Schmeling, Anton Schulze, Paul Walter, Philip Wiemer
logo: quadriga-logo.jpeg
copyright: "2024, QUADRIGA" 
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", R_Lerneinheit.ipynb, 3.ipynb, conda, venv, README.md, LICENSE.md, .github, Checkliste_Finalisierung.md, "Markdown/md_*.md"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/quadriga-dk/Tabelle-Fallstudie-1  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: jupyterlab # remove if you don't want to use binder
  binderhub_url: https://mybinder.org # remove if you don't want to use binder
  colab_url: https://colab.research.google.com
  jupyterhub_url: https://dev.jupyterhub.uni-potsdam.de
  thebe: true
  
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <p xmlns:cc="http://creativecommons.org/ns#" >This work is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a>. For more detailed information please refer to <a href="https://github.com/quadriga-dk/Book_Template/blob/main/LICENSE.md">LICENSE.md</a></p>
  use_multitoc_numbering: false

sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false
    html_static_path: ['_static']
    html_css_files:
      - quadriga.css
      - carousel.css
    html_js_files:
      - carousel.js
