name: Deploy Book

on:
  workflow_run:
    workflows: ["Update Metadata"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
        restore-keys: ${{ runner.os }}-r-

    - name: Install IRkernel
      run: |
        Rscript -e "install.packages('IRkernel')"
        
    - name: Print kernelspec version
      run: |
        jupyter kernelspec --version

    - name: Print all kernels
      run: |
        jupyter kernelspec list

    - name: Register IRkernel
      run: |
        Rscript -e "IRkernel::installspec()"

    - name: Print all kernels again
      run: |
        jupyter kernelspec list

    # (optional) Cache your executed notebooks between runs
    # if you have config:
    # execute:
    #   execute_notebooks: cache
    - name: cache executed notebooks
      uses: actions/cache@v4
      with:
        path: _build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    - name: Build the book
      run: |
        jupyter-book build .

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_build/html"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
